deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp dbConnect.php $DEPLOYPATH
    - /bin/cp session.php $DEPLOYPATH

    - /bin/cp -R admin-panel $DEPLOYPATH
    - /bin/cp -R login $DEPLOYPATH
    - /bin/cp -R s-exam $DEPLOYPATH